# (C) Copyright 2019-2021 Syncsort Incorporated. All rights reserved.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ibm-pem-psp"
  labels:
    app: "ibm-pem-psp"
rules:
- apiGroups:
  - policy
  resourceNames:
  - "ibm-pem-psp"
  resources:
  - podsecuritypolicies
  verbs:
  - use
