# (C) Copyright 2019-2021 Syncsort Incorporated. All rights reserved.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ibm-pem-scc"
  labels:
    app: "ibm-pem-scc" 
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - "ibm-pem-scc"
  resources:
  - securitycontextconstraints
  verbs:
  - use
