apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "270"
  name: "ibm-sccm-scc"
  labels:
    app: "ibm-sccm-scc"
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-sccm-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use