apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-cp4ba-operator-group
  namespace: cp4ba
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  targetNamespaces:
  - cp4ba